#include <iostream>
#include <time.h>

#include "Rand.h"

const int NUM_BYTES = 10;

int main()
{
  // Create functor, with seed set using time()
  Rand::genRand genRandBytes(NUM_BYTES, time(NULL));
  
  // Generate bytes
  uint8_t* p = genRandBytes();

  if(p != nullptr)
  {
    // Display generated bytes
    for(int i = 0; i < NUM_BYTES; i++)
    {
      std::cout << "[Byte " << i << "]: " << (int)p[i] << std::endl;
    }
  }
  else
  {
    std::cout << "Error: nullptr was returned" << std::endl;
  }

  return 0;
}